# """
# Django settings for oj project.

# Generated by 'django-admin startproject' using Django 1.11.

# For more information on this file, see
# https://docs.djangoproject.com/en/1.8/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.8/ref/settings/
# """
# import os
# import raven
# from copy import deepcopy
# from utils.shortcuts import get_env

# production_env = get_env("OJ_ENV", "dev") == "production"
# if production_env:
#     from .production_settings import *
# else:
#     from .dev_settings import *

# with open(os.path.join(DATA_DIR, "config", "secret.key"), "r") as f:
#     SECRET_KEY = f.read()

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# # Applications
# VENDOR_APPS = [
#     'django.contrib.auth',
#     'django.contrib.sessions',
#     'django.contrib.contenttypes',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'django_dramatiq',
#     'django_dbconn_retry',
# ]

# if production_env:
#     VENDOR_APPS.append('raven.contrib.django.raven_compat')


# LOCAL_APPS = [
#     'account',
#     'announcement',
#     'conf',
#     'problem',
#     'contest',
#     'utils',
#     'submission',
#     'options',
#     'judge',
# ]

# INSTALLED_APPS = VENDOR_APPS + LOCAL_APPS

# MIDDLEWARE = (
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'account.middleware.APITokenAuthMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'account.middleware.AdminRoleRequiredMiddleware',
#     'account.middleware.SessionRecordMiddleware',
#     # 'account.middleware.LogSqlMiddleware',
# )
# ROOT_URLCONF = 'oj.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
# WSGI_APPLICATION = 'oj.wsgi.application'

# # Password validation
# # https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalization
# # https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/public/'

# AUTH_USER_MODEL = 'account.User'

# TEST_CASE_DIR = os.path.join(DATA_DIR, "test_case")
# LOG_PATH = os.path.join(DATA_DIR, "log")

# AVATAR_URI_PREFIX = "/public/avatar"
# AVATAR_UPLOAD_DIR = f"{DATA_DIR}{AVATAR_URI_PREFIX}"

# UPLOAD_PREFIX = "/public/upload"
# UPLOAD_DIR = f"{DATA_DIR}{UPLOAD_PREFIX}"

# STATICFILES_DIRS = [os.path.join(DATA_DIR, "public")]


# LOGGING_HANDLERS = ['console', 'sentry'] if production_env else ['console']
# LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'formatters': {
#        'standard': {
#            'format': '[%(asctime)s] - [%(levelname)s] - [%(name)s:%(lineno)d]  - %(message)s',
#            'datefmt': '%Y-%m-%d %H:%M:%S'
#        }
#    },
#    'handlers': {
#        'console': {
#            'level': 'DEBUG',
#            'class': 'logging.StreamHandler',
#            'formatter': 'standard'
#        },
#        'sentry': {
#            'level': 'ERROR',
#            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
#            'formatter': 'standard'
#        }
#    },
#    'loggers': {
#        'django.request': {
#            'handlers': LOGGING_HANDLERS,
#            'level': 'ERROR',
#            'propagate': True,
#        },
#        'django.db.backends': {
#            'handlers': LOGGING_HANDLERS,
#            'level': 'ERROR',
#            'propagate': True,
#        },
#         'dramatiq': {
#             'handlers': LOGGING_HANDLERS,
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#        '': {
#            'handlers': LOGGING_HANDLERS,
#            'level': 'WARNING',
#            'propagate': True,
#        }
#    },
# }

# REST_FRAMEWORK = {
#     'TEST_REQUEST_DEFAULT_FORMAT': 'json',
#     'DEFAULT_RENDERER_CLASSES': (
#         'rest_framework.renderers.JSONRenderer',
#     )
# }

# REDIS_URL = "redis://%s:%s" % (REDIS_CONF["host"], REDIS_CONF["port"])


# def redis_config(db):
#     def make_key(key, key_prefix, version):
#         return key

#     return {
#         "BACKEND": "utils.cache.MyRedisCache",
#         "LOCATION": f"{REDIS_URL}/{db}",
#         "TIMEOUT": None,
#         "KEY_PREFIX": "",
#         "KEY_FUNCTION": make_key
#     }


# CACHES = {
#     "default": redis_config(db=1)
# }

# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# DRAMATIQ_BROKER = {
#     "BROKER": "dramatiq.brokers.redis.RedisBroker",
#     "OPTIONS": {
#         "url": f"{REDIS_URL}/4",
#     },
#     "MIDDLEWARE": [
#         # "dramatiq.middleware.Prometheus",
#         "dramatiq.middleware.AgeLimit",
#         "dramatiq.middleware.TimeLimit",
#         "dramatiq.middleware.Callbacks",
#         "dramatiq.middleware.Retries",
#         # "django_dramatiq.middleware.AdminMiddleware",
#         "django_dramatiq.middleware.DbConnectionsMiddleware"
#     ]
# }

# DRAMATIQ_RESULT_BACKEND = {
#     "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
#     "BACKEND_OPTIONS": {
#         "url": f"{REDIS_URL}/4",
#     },
#     "MIDDLEWARE_OPTIONS": {
#         "result_ttl": None
#     }
# }

# RAVEN_CONFIG = {
#     'dsn': 'https://b200023b8aed4d708fb593c5e0a6ad3d:1fddaba168f84fcf97e0d549faaeaff0@sentry.io/263057'
# }

# IP_HEADER = "HTTP_X_REAL_IP"

# DEFAULT_AUTO_FIELD='django.db.models.AutoField'

import os

# =======================
# Base directory
# =======================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = BASE_DIR  # can be adjusted if you have a separate data folder

# =======================
# Debug / Hosts
# =======================
DEBUG = True
ALLOWED_HOSTS = ["*"]  # allow all hosts for local development

# =======================
# Secret Key
# =======================
# Create a secret.key file in DATA_DIR/config/secret.key or generate one
SECRET_KEY_FILE = os.path.join(DATA_DIR, "config", "secret.key")
if os.path.exists(SECRET_KEY_FILE):
    with open(SECRET_KEY_FILE, "r") as f:
        SECRET_KEY = f.read().strip()
else:
    # fallback key for local dev
    SECRET_KEY = "local-dev-secret-key"

# =======================
# Applications
# =======================
INSTALLED_APPS = [
    # Django
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'django_dramatiq',
    'django_dbconn_retry',
    'drf_yasg',

    # Local apps
    'account',
    'announcement',
    'conf',
    'problem',
    'contest',
    'utils',
    'submission',
    'options',
    'judge',
]

# =======================
# Middleware
# =======================
MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'account.middleware.APITokenAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.AdminRoleRequiredMiddleware',
    'account.middleware.SessionRecordMiddleware',
)

ROOT_URLCONF = 'oj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ← custom templates dir: overrides drf_yasg/templates/drf-yasg/swagger-ui.html
        #   with our CSRF-injecting version
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oj.wsgi.application'

# =======================
# Django REST Framework
# =======================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Session auth: reads the sessionid cookie set by Django's login view.
        # Swagger UI's 'credentials: include' setting ensures the cookie is sent.
        'rest_framework.authentication.SessionAuthentication',
        # BasicAuth: fallback for quick curl testing (username:password)
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # All endpoints start as open; individual views apply their own guards
        # (login_required, super_admin_required, etc.)
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# =======================
# CSRF Trusted origins (allows Swagger UI "Try it out" from localhost)
# =======================
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://0.0.0.0:8000',
]

# =======================
# Password validation
# =======================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =======================
# Internationalization
# =======================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# =======================
# Static & Uploads
# =======================
STATIC_URL = '/public/'
STATICFILES_DIRS = [os.path.join(DATA_DIR, "public")]

# Uploads
AVATAR_URI_PREFIX = "/public/avatar"
AVATAR_UPLOAD_DIR = os.path.join(DATA_DIR, "public", "avatar")
UPLOAD_PREFIX = "/public/upload"
UPLOAD_DIR = os.path.join(DATA_DIR, "public", "upload")
TEST_CASE_DIR = os.path.join(DATA_DIR, "test_case")
LOG_PATH = os.path.join(DATA_DIR, "log")

# =======================
# Database (PostgreSQL in Docker)
# =======================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'onlinejudge',
        'USER': 'onlinejudge',
        'PASSWORD': 'onlinejudge',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


SWAGGER_SETTINGS = {
    # ── Authentication ────────────────────────────────────────────────────────
    "USE_SESSION_AUTH": True,

    "SECURITY_DEFINITIONS": {
        "SessionAuth": {
            "type": "apiKey",
            "in": "cookie",
            "name": "sessionid",
            "description": (
                "Session-based authentication. "
                "Login via POST /api/account/login/; the `sessionid` cookie is set automatically. "
                "Then click Authorize here and enter your session ID value."
            ),
        },
        "ApiKeyAuth": {
            "type": "apiKey",
            "in": "header",
            "name": "APPKEY",
            "description": (
                "API Key authentication for Open-API access. "
                "1. Enable Open API for your account via the admin panel. "
                "2. POST to /api/account/appkey/ to get your AppKey. "
                "3. Enter the key here (the header name is APPKEY)."
            ),
        },
    },

    # ── UI Configuration ──────────────────────────────────────────────────────
    "DEFAULT_AUTO_SCHEMA_CLASS": "drf_yasg.inspectors.SwaggerAutoSchema",

    # Show all endpoints expanded by default
    "OPERATIONS_SORTER": "alpha",
    "TAGS_SORTER": "alpha",
    "DOC_EXPANSION": "none",          # collapsed by default – less clutter
    "DEEP_LINKING": True,             # bookmarkable URLs per endpoint
    "SHOW_EXTENSIONS": True,
    "NATIVE_SETTINGS": False,
    "REFETCH_SCHEMA_WITH_AUTH": True,
    "REFETCH_SCHEMA_ON_LOGOUT": True,

    # Disable external validator (works offline / no internet needed)
    "VALIDATOR_URL": None,

    # Persist auth across page refreshes (stored in localStorage)
    "PERSIST_AUTH": True,

    # Show operation ID above each endpoint (useful for debugging)
    "DISPLAY_OPERATION_ID": True,

    # ── Login / Logout for drf-yasg session auth widget ──────────────────────
    # The "Django Login" button in Swagger redirects here so you can log in
    # and come back to the Swagger page with a live session cookie
    "LOGIN_URL": "/api/account/login/",
    "LOGOUT_URL": "/api/account/logout/",

    # ── Supported request content types (for 'Try it out') ───────────────────
    "SUPPORTED_SUBMIT_METHODS": [
        "get", "post", "put", "delete", "patch"
    ],

    # ── Default model rendering ───────────────────────────────────────────────
    "DEFAULT_MODEL_RENDERING": "example",  # show example values, not schema tree
    "DEFAULT_MODEL_DEPTH": 2,
}




# =======================
# Redis
# =======================
REDIS_CONF = {
    "host": "127.0.0.1",
    "port": "6379",
}

# REDIS_CONF = {
#     "host": "oj-redis",   # Docker service name
#     "port": "6379",
# }

REDIS_URL = f"redis://{REDIS_CONF['host']}:{REDIS_CONF['port']}"

def redis_config(db):
    def make_key(key, key_prefix, version):
        return key
    return {
        "BACKEND": "utils.cache.MyRedisCache",
        "LOCATION": f"{REDIS_URL}/{db}",
        "TIMEOUT": None,
        "KEY_PREFIX": "",
        "KEY_FUNCTION": make_key
    }

CACHES = {"default": redis_config(db=1)}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# =======================
# DramatIQ
# =======================
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": {"url": f"{REDIS_URL}/4"},
    "MIDDLEWARE": [
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
    ],
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
    "BACKEND_OPTIONS": {"url": f"{REDIS_URL}/4"},
    "MIDDLEWARE_OPTIONS": {"result_ttl": None},
}

# =======================
# Rest Framework
# =======================
REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}

# =======================
# Misc
# =======================
AUTH_USER_MODEL = 'account.User'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
IP_HEADER = "HTTP_X_REAL_IP"

# =======================
# Logging (simple for dev)
# =======================
LOGGING_HANDLERS = ['console']
LOGGING = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
       'standard': {
           'format': '[%(asctime)s] - [%(levelname)s] - [%(name)s:%(lineno)d] - %(message)s',
           'datefmt': '%Y-%m-%d %H:%M:%S'
       }
   },
   'handlers': {
       'console': {
           'level': 'DEBUG',
           'class': 'logging.StreamHandler',
           'formatter': 'standard'
       }
   },
   'loggers': {
       'django.request': {
           'handlers': LOGGING_HANDLERS,
           'level': 'ERROR',
           'propagate': True,
       },
       'django.db.backends': {
           'handlers': LOGGING_HANDLERS,
           'level': 'ERROR',
           'propagate': True,
       },
       'dramatiq': {
           'handlers': LOGGING_HANDLERS,
           'level': 'DEBUG',
           'propagate': False,
       },
       '': {
           'handlers': LOGGING_HANDLERS,
           'level': 'WARNING',
           'propagate': True,
       }
   },
}
